repo: jsdelivr
owner: jsdelivr

user: jsdelivrbot
auth_token: # token
post_secret: # secret

merge_re: "@jsdelivrbot (.* )?squ[ia]sh.*"

# For squash&merging
path_to_repo: ~\jsdelivr
repo_branch: master
repo_upstream: origin

# Users to auto merge prs from
trusted_users:
  - jsdelivrbot