repo: jsdelivr
owner: jsdelivr

user: jsdelivrbot
auth_token: # token
post_secret: # secret

merge_re: "\s*@jsdelivrbot squash (and|&) merge\s*"

path_to_repo: ~\jsdelivr

# Users to auto merge prs from
trusted_users:
  - jsdelivrbot